### ISSUE TITLE
Google Contacts

### ISSUE THREAD

**Issue by jfinstrom** [POSSA/Caller-ID-Superfecta#210] opened 2014-07-31 23:36 UTC
##Feature Request
------------------------------------------------------
Google contacts module

**Comment by ntadmin** [comment] 2015-04-17 16:54
I have developed some working php code which provides caller id from a user's google contacts, including authentication etc. I am more than happy to help integrate this into CID superfecta.

However:

1. CID superfecta doesn't currently work on my raspberry asterisk pbx. All is up to date as far as I can tell. If someone can help me solve this, that would be great.

2. Some advice on how to integrate new modules into superfecta would be much appreciated!

Neil

**Comment by ntadmin** [comment] 2015-04-20 19:15
OK, I now have Google contacts fully working within superfecta. How do I get it added as a 'proper' part?

**Comment by lgaetz** [comment] 2015-04-21 00:56
Are you comfortable working with Git? If so you can fork this project to your github account, commit your changes there then issue a pull request back to this project. If you want you can just zip up your superfecta directory and contents and email to me and I can sort it out. 

Did you ever figure out what was preventing superfecta from working with your pi?

**Comment by ntadmin** [comment] 2015-04-21 18:46
ps, yes, I did. The issue lies with a js file not being where it is expected to be. I'm away from my machine at the moment, when I send the source code I'll send a specific issue description. My solution was to slap a symbolic link in, which got it going but the issue is probably where it is looking for the file.


Neil

**Comment by ntadmin** [comment] 2015-04-21 18:47
Hi Lorne,

     I must admit that I've never used git, so it's probably a bit risky to use this as a first try. I will zip up the files and send them to you (it may be a few days until I am next able to give time to this particular thing).

     I will be interested to know if it works for you, and if the way I have set it up is clear. To make it work I have had to 'push' the superfecta framework in two ways:

1. Because requires web based user agreement, and some internal codes, and so I have had to create a process. Ideally there would be a hook on the 'submit' button which the method can catch and trigger things (ideally even a new window/tab at specific location).

2. It needs to store information which the user doesn't need to see. It would be cleaner if the parameters could have a "hidden" type which could be changed but which didn't appear for the user. Ideally there would be a more formalised way of updating this information rather than doing direct sql based on the code.

     I'm happy to help with these kind of improvements, and I can see how to do them, but don't want to invest time and energy if they will not be adopted.

     Cheers,

     Neil

**Comment by ntadmin** [comment] 2015-04-23 08:58
I'll try and do this step at a time

First: superfecta not working is down do the request from the page for some javascript files at the wrong place. The file in question is

admin/modules/superfecta/assets/js/query.form.js 

but it seems to be asking for ti from

admin/superfecta/endpointman/js

My solution was to slap in a symbolic link, but this is probably not the right way. Clearly there is a path issue either in the server or the page.

**Comment by ntadmin** [comment] 2015-04-23 09:28
Now, the three steps for google contacts, step 1

We need to have up to date autorisation code for google. Thankfully, it is available from google.

[m/s/ == /modules/superfecta]

Create a directory: m/s/includes/oauth-google

Put in the the directoray (and all it's contents) from the Google php auth code from https://github.com/google/google-api-php-client

You should now have /m/s/includes/oauth-google which looks like:

drwxr-xr-x 10 neil neil  4096 Apr 18 14:18 .
drwxr-xr-x  3 neil neil  4096 Apr 18 14:18 ..
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 Auth
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 Cache
-rw-r--r--  1 neil neil 18884 Apr  8 10:47 Client.php
-rw-r--r--  1 neil neil  2448 Apr  8 10:47 Collection.php
-rw-r--r--  1 neil neil 11031 Apr  8 10:47 Config.php
-rw-r--r--  1 neil neil   647 Apr  8 10:47 Exception.php
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 Http
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 IO
-rw-r--r--  1 neil neil  7212 Apr  8 10:47 Model.php
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 Service
-rw-r--r--  1 neil neil   978 Apr  8 10:47 Service.php
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 Signer
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 Utils
-rw-r--r--  1 neil neil  3993 Apr  8 10:47 Utils.php
drwxr-xr-x  2 neil neil  4096 Apr  8 10:47 Verifier

**Comment by ntadmin** [comment] 2015-04-23 09:35
Step 2: Add in a couple of classes to make using the Google Code and getting contacts smoother.

Get these two files in

https://www.dropbox.com/s/exkmt8qdauezicx/Google_Service_ReadContacts.php?dl=0
https://www.dropbox.com/s/e4rp8dcfdz86ap4/GoogleAuthManager.php?dl=0

and put them in

/m/s/includes/oauth-google

That directory should now contain:

Google
GoogleAuthManager.php
Google_Service_ReadContacts.php

**Comment by ntadmin** [comment] 2015-04-23 09:36
Step 3: The code the interfaces with superfecata

Get the file:

https://www.dropbox.com/s/lenvbkkrgc4wccv/source-GoogleContacts.module?dl=0

Put it in

/m/s/sources

And then it seemed to work.

**Comment by ntadmin** [comment] 2015-04-23 09:40
All comments, suggestions for improvement etc welcome.

As I've hinted above, it would be made a little cleaner if:

a) The idea of 'internal' parameters could be added to the types of parameters. These wouldn't even need to be shown to the user.

b) The 'source-XXXXXX.module' code had access to a method for updating those internal parameters, something like:

$this->updateParameter('Paramater_Name', $new_value);

I suspect that this could be added to suprefecta_base.php, but I didn't want to mess with too much on my first go. This would mean that that the sql code was somewhere better than in the source-XXXXX.module code.

**Comment by ntadmin** [comment] 2015-04-27 10:12
OK, I've tried to push all these up using git, and it seems to work, right up to the final command:  git-push. Here's the sequence

neil@raspbx:~/git/Caller-ID-Superfecta$ git push
Username for 'https://github.com': ntadmin
Password for 'https://ntadmin@github.com':
remote: Permission to POSSA/Caller-ID-Superfecta.git denied to ntadmin.
fatal: unable to access 'https://github.com/POSSA/Caller-ID-Superfecta.git/': The requested URL returned error: 403
neil@raspbx:~/git/Caller-ID-Superfecta$

Is there an authorisation issue? I tried it several times and always got the same result.

**Comment by lgaetz** [comment] 2015-04-27 16:19
You do not have priv's to push to POSSA repos directly. You must first 'fork' the repo to your own github account, commit changes to your own fork, then signal to us that you want to share your code by sending us a 'merge request'. I have noted your contribution via dropbox, but I have been pressed for time lately and have been unable to evaluate it. It is on my list of things to do.

Quoted from above:

> I'm happy to help with these kind of improvements, and I can see how to do them, but don't want to invest time and energy if they will not be adopted.

We absolutely welcome and encourage submissions, but before we accept any contributions you must first file a completed code submission agreement:
http://wiki.freepbx.org/display/DC/Code+License+Agreement

Thanks

**Comment by ntadmin** [comment] 2015-04-28 08:37
CLA emailed, I expect to be able to get back to the project later this 
week and will try the git route again, it will be a good learning 
experience.

Neil

**Comment by tm1000** [comment] 2015-04-28 13:14
Thanks Neil. You are approved

**Comment by ntadmin** [comment] 2015-04-28 14:50
Thanks,

Neil

**Comment by ntadmin** [comment] 2015-04-28 15:22
Hi Lorne,

     Had a few minutes unexpectedly spare today, so I've done what I 
think you suggested - you should have a pull/merge request I think.

     Neil

**Comment by tm1000** [comment] 2015-05-20 14:58
This has bee completed.

**Closed by tm1000** 2015-05-20 14:58 UTC
Labels: module feature
